In [1]:
import pandas as pd

# Welcome to the Causal Wonderland!

Below you'll find a small warm-up exercise that will help us build a common ground in the first part of the session.


## Your Warm-Up Exercise: Instructions

Imagine you're in the following situation:

Marc and Nathalie want to understand whether, and how much, of a discount they should offer their customers to maximize profit.

They have received two historical datasets containing a number of variables that describe the customers and their behaviors ($X$), as well as the outcome variable quantifying customer spending ($Y$).

Using the technique(s) of your choice, can you help Marc and Nathalie quantify the effect of the discount amount ($X_1$) on spending ($Y$)?

In particular, can you help them answer the question: **What is the effect of $X_1$ on $Y$?**

At the end of the notebook, you'll find a **link to submit your answer** 

The code below will load the data for you.

In [2]:
# Read the data - dataset 1
df1 = pd.read_csv('https://raw.githubusercontent.com/AlxndrMlk/talks-and-workshops/refs/heads/main/2025-09--lingaro/data/dataset1.csv')
df2 = pd.read_csv('https://raw.githubusercontent.com/AlxndrMlk/talks-and-workshops/refs/heads/main/2025-09--lingaro/data/dataset2.csv')

In [3]:
df1.head()

         x1        x2          x3        x4        x5          y
0  3.943921  1.772409 -116.710972  0.906105  7.897970   6.044647
1  2.608663  1.208288  -84.433272  1.644846  6.158114   4.373869
2  6.015692  2.754239 -194.561517  1.714756  5.248536  10.138947
3  7.580054  3.426146 -219.975157  0.832489  2.563980  11.373965
4  2.674613  1.004589  -55.893137  0.872053  6.463233   2.815693

In [4]:
df2.head()

         x1        x2          x3        x4        x5          y
0  0.559138  0.748775  -83.632316 -0.303856  5.768980   4.610812
1  0.148562  6.110549 -860.551168  1.432733  2.076002  47.770659
2  0.016396  3.916971 -556.547168  0.373476  3.160459  30.914869
3  0.022395  3.475846 -491.014252 -0.288874  4.407236  27.279331
4  0.076919  3.563278 -522.913910  0.069021  5.142340  29.063909

### Your solution:

In [ ]:
# YOUR CODE HERE

### Submit your answer [here](https://share.deftform.com/causalpython-lingaro-talk-wEZVwb)